Repository TmaxFintech/fintech-arena-be, pull requests merged in 2022-09, with the labels that each got.

#6 게시판 서비스 유즈케이스 작성
  document/use-case.drawio.svg
Labels: documentation

#8 스프링 부트 프로젝트 시작
  fintech-arena-be/.gitignore
  fintech-arena-be/build.gradle
  fintech-arena-be/gradle/wrapper/gradle-wrapper.jar
  fintech-arena-be/gradle/wrapper/gradle-wrapper.properties
  fintech-arena-be/gradlew
  fintech-arena-be/gradlew.bat
  fintech-arena-be/settings.gradle
  fintech-arena-be/src/main/java/com/tmaxfintech/fintecharenabe/FintechArenaBeApplication.java
  fintech-arena-be/src/main/resources/application.properties
  fintech-arena-be/src/test/java/com/tmaxfintech/fintecharenabe/FintechArenaBeApplicationTests.java
Labels: enhancement

#10 도메인 설계
  document/fintech-arena-board-erd.svg
  fintech-arena-be/src/main/java/com/tmaxfintech/fintecharenabe/domain/Article.java
  fintech-arena-be/src/main/java/com/tmaxfintech/fintecharenabe/domain/ArticleComment.java
Labels: documentation, enhancement

#28 DB 접속 유저 및 비밀번호 변경 - 우선은 root 유저로 설정
  src/main/resources/application.yml
Labels: enhancement, fix

#30 .gitignore 에 jpa buddy 플러그인의 설정 파일을 무시하도록 룰 추가
  .gitignore
Labels: enhancement

#33 게시글, 댓글, 유저 계정 ERD 업데이트 및 벡터 이미지 수정
  document/fintech-arena-board-erd.svg
  document/project-board-erd.svg
  document/use-case.drawio.svg
  document/use-case.svg
  src/main/java/com/tmaxfintech/fintecharenabe/domain/Article.java
  src/main/java/com/tmaxfintech/fintecharenabe/domain/ArticleComment.java
  src/main/resources/data.sql
Labels: enhancement

#34 게시글, 댓글, 유저 계정 ERD 업데이트 및 벡터 이미지 수정 - 테스트 코드 수정
  src/test/java/com/tmaxfintech/fintecharenabe/repository/JpaRepositoryTest.java
Labels: enhancement

#35 게시판 서비스 뷰에 기능 구현하기
  .gitignore
  src/main/java/com/tmaxfintech/fintecharenabe/controller/MainController.java
  src/main/java/com/tmaxfintech/fintecharenabe/domain/Article.java
  src/main/java/com/tmaxfintech/fintecharenabe/domain/ArticleComment.java
  src/main/java/com/tmaxfintech/fintecharenabe/domain/type/SearchType.java
  src/main/java/com/tmaxfintech/fintecharenabe/dto/ArticleCommentDto.java
  src/main/java/com/tmaxfintech/fintecharenabe/dto/ArticleDto.java
  src/main/java/com/tmaxfintech/fintecharenabe/dto/ArticleUpdateDto.java
  src/main/java/com/tmaxfintech/fintecharenabe/dto/ArticleWithCommentsDto.java
  src/main/java/com/tmaxfintech/fintecharenabe/dto/UserAccountDto.java
  src/main/java/com/tmaxfintech/fintecharenabe/dto/response/ArticleCommentResponse.java
  src/main/java/com/tmaxfintech/fintecharenabe/dto/response/ArticleResponse.java
  src/main/java/com/tmaxfintech/fintecharenabe/dto/response/ArticleWithCommentsResponse.java
  src/main/java/com/tmaxfintech/fintecharenabe/repository/ArticleCommentRepository.java
  src/main/java/com/tmaxfintech/fintecharenabe/repository/ArticleRepository.java
  src/main/java/com/tmaxfintech/fintecharenabe/service/ArticleCommentService.java
  src/main/java/com/tmaxfintech/fintecharenabe/service/ArticleService.java
  src/main/resources/application.yml
  src/test/java/com/tmaxfintech/fintecharenabe/controller/MainControllerTest.java
  src/test/java/com/tmaxfintech/fintecharenabe/repository/JpaRepositoryTest.java
  src/test/java/com/tmaxfintech/fintecharenabe/service/ArticleCommentServiceTest.java
  src/test/java/com/tmaxfintech/fintecharenabe/service/ArticleServiceTest.java
Labels: enhancement

#36 게시판 서비스 뷰에 기능 구현하기 - 뷰까지 구현 완료
  src/main/java/com/tmaxfintech/fintecharenabe/controller/ArticleController.java
  src/main/java/com/tmaxfintech/fintecharenabe/domain/Article.java
  src/main/resources/data.sql
  src/main/resources/templates/articles/detail.html
  src/main/resources/templates/articles/detail.th.xml
  src/main/resources/templates/articles/index.html
  src/main/resources/templates/articles/index.th.xml
  src/test/java/com/tmaxfintech/fintecharenabe/controller/ArticleControllerTest.java
Labels: enhancement

#37 게시판 서비스 뷰에 기능 구현하기
  .gitignore
  src/main/java/com/tmaxfintech/fintecharenabe/controller/ArticleController.java
  src/main/java/com/tmaxfintech/fintecharenabe/controller/MainController.java
  src/main/java/com/tmaxfintech/fintecharenabe/domain/Article.java
  src/main/java/com/tmaxfintech/fintecharenabe/domain/ArticleComment.java
  src/main/java/com/tmaxfintech/fintecharenabe/domain/type/SearchType.java
  src/main/java/com/tmaxfintech/fintecharenabe/dto/ArticleCommentDto.java
  src/main/java/com/tmaxfintech/fintecharenabe/dto/ArticleDto.java
  src/main/java/com/tmaxfintech/fintecharenabe/dto/ArticleUpdateDto.java
  src/main/java/com/tmaxfintech/fintecharenabe/dto/ArticleWithCommentsDto.java
  src/main/java/com/tmaxfintech/fintecharenabe/dto/UserAccountDto.java
  src/main/java/com/tmaxfintech/fintecharenabe/dto/response/ArticleCommentResponse.java
  src/main/java/com/tmaxfintech/fintecharenabe/dto/response/ArticleResponse.java
  src/main/java/com/tmaxfintech/fintecharenabe/dto/response/ArticleWithCommentsResponse.java
  src/main/java/com/tmaxfintech/fintecharenabe/repository/ArticleCommentRepository.java
  src/main/java/com/tmaxfintech/fintecharenabe/repository/ArticleRepository.java
  src/main/java/com/tmaxfintech/fintecharenabe/service/ArticleCommentService.java
  src/main/java/com/tmaxfintech/fintecharenabe/service/ArticleService.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/templates/articles/detail.html
  src/main/resources/templates/articles/detail.th.xml
  src/main/resources/templates/articles/index.html
  src/main/resources/templates/articles/index.th.xml
  src/test/java/com/tmaxfintech/fintecharenabe/controller/ArticleControllerTest.java
  src/test/java/com/tmaxfintech/fintecharenabe/controller/MainControllerTest.java
  src/test/java/com/tmaxfintech/fintecharenabe/repository/JpaRepositoryTest.java
  src/test/java/com/tmaxfintech/fintecharenabe/service/ArticleCommentServiceTest.java
  src/test/java/com/tmaxfintech/fintecharenabe/service/ArticleServiceTest.java
Labels: enhancement

#42 잘못된 도메인 정보 바로잡기
  src/main/java/com/tmaxfintech/fintecharenabe/controller/ArticleController.java
  src/main/java/com/tmaxfintech/fintecharenabe/domain/UserAccount.java
  src/main/java/com/tmaxfintech/fintecharenabe/service/PaginationService.java
  src/main/resources/static/css/articles/table-header.css
  src/main/resources/templates/articles/index.html
  src/main/resources/templates/articles/index.th.xml
  src/test/java/com/tmaxfintech/fintecharenabe/controller/ArticleControllerTest.java
  src/test/java/com/tmaxfintech/fintecharenabe/service/PaginationServiceTest.java
Labels: enhancement

#46 DB서버 위치 이전에 따른 설정 변경
  src/main/resources/application.yml
Labels: enhancement, fix

#48 CI job에서 test 제외(임시)
  Jenkinsfile
Labels: enhancement, fix
